/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeworkRouteImport } from './routes/homework'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as HomeworkIndexRouteImport } from './routes/homework.index'
import { Route as HomeworkNewRouteImport } from './routes/homework.new'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as HomeworkDraftsHomeworkDraftIdRouteImport } from './routes/homework.drafts.$homeworkDraftId'
import { Route as StudentsStudentIdHistoryRouteImport } from './routes/students.$studentId.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkRoute = HomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeworkIndexRoute = HomeworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeworkRoute,
} as any)
const HomeworkNewRoute = HomeworkNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => HomeworkRoute,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const HomeworkDraftsHomeworkDraftIdRoute =
  HomeworkDraftsHomeworkDraftIdRouteImport.update({
    id: '/drafts/$homeworkDraftId',
    path: '/drafts/$homeworkDraftId',
    getParentRoute: () => HomeworkRoute,
  } as any)
const StudentsStudentIdHistoryRoute =
  StudentsStudentIdHistoryRouteImport.update({
    id: '/$studentId/history',
    path: '/$studentId/history',
    getParentRoute: () => StudentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/homework': typeof HomeworkRouteWithChildren
  '/insights': typeof InsightsRoute
  '/students': typeof StudentsRouteWithChildren
  '/homework/new': typeof HomeworkNewRoute
  '/homework/': typeof HomeworkIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/homework/drafts/$homeworkDraftId': typeof HomeworkDraftsHomeworkDraftIdRoute
  '/students/$studentId/history': typeof StudentsStudentIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/homework/new': typeof HomeworkNewRoute
  '/homework': typeof HomeworkIndexRoute
  '/students': typeof StudentsIndexRoute
  '/homework/drafts/$homeworkDraftId': typeof HomeworkDraftsHomeworkDraftIdRoute
  '/students/$studentId/history': typeof StudentsStudentIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/homework': typeof HomeworkRouteWithChildren
  '/insights': typeof InsightsRoute
  '/students': typeof StudentsRouteWithChildren
  '/homework/new': typeof HomeworkNewRoute
  '/homework/': typeof HomeworkIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/homework/drafts/$homeworkDraftId': typeof HomeworkDraftsHomeworkDraftIdRoute
  '/students/$studentId/history': typeof StudentsStudentIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/homework'
    | '/insights'
    | '/students'
    | '/homework/new'
    | '/homework/'
    | '/students/'
    | '/homework/drafts/$homeworkDraftId'
    | '/students/$studentId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/homework/new'
    | '/homework'
    | '/students'
    | '/homework/drafts/$homeworkDraftId'
    | '/students/$studentId/history'
  id:
    | '__root__'
    | '/'
    | '/homework'
    | '/insights'
    | '/students'
    | '/homework/new'
    | '/homework/'
    | '/students/'
    | '/homework/drafts/$homeworkDraftId'
    | '/students/$studentId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeworkRoute: typeof HomeworkRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework': {
      id: '/homework'
      path: '/homework'
      fullPath: '/homework'
      preLoaderRoute: typeof HomeworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homework/': {
      id: '/homework/'
      path: '/'
      fullPath: '/homework/'
      preLoaderRoute: typeof HomeworkIndexRouteImport
      parentRoute: typeof HomeworkRoute
    }
    '/homework/new': {
      id: '/homework/new'
      path: '/new'
      fullPath: '/homework/new'
      preLoaderRoute: typeof HomeworkNewRouteImport
      parentRoute: typeof HomeworkRoute
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/homework/drafts/$homeworkDraftId': {
      id: '/homework/drafts/$homeworkDraftId'
      path: '/drafts/$homeworkDraftId'
      fullPath: '/homework/drafts/$homeworkDraftId'
      preLoaderRoute: typeof HomeworkDraftsHomeworkDraftIdRouteImport
      parentRoute: typeof HomeworkRoute
    }
    '/students/$studentId/history': {
      id: '/students/$studentId/history'
      path: '/$studentId/history'
      fullPath: '/students/$studentId/history'
      preLoaderRoute: typeof StudentsStudentIdHistoryRouteImport
      parentRoute: typeof StudentsRoute
    }
  }
}

interface HomeworkRouteChildren {
  HomeworkNewRoute: typeof HomeworkNewRoute
  HomeworkIndexRoute: typeof HomeworkIndexRoute
  HomeworkDraftsHomeworkDraftIdRoute: typeof HomeworkDraftsHomeworkDraftIdRoute
}

const HomeworkRouteChildren: HomeworkRouteChildren = {
  HomeworkNewRoute: HomeworkNewRoute,
  HomeworkIndexRoute: HomeworkIndexRoute,
  HomeworkDraftsHomeworkDraftIdRoute: HomeworkDraftsHomeworkDraftIdRoute,
}

const HomeworkRouteWithChildren = HomeworkRoute._addFileChildren(
  HomeworkRouteChildren,
)

interface StudentsRouteChildren {
  StudentsIndexRoute: typeof StudentsIndexRoute
  StudentsStudentIdHistoryRoute: typeof StudentsStudentIdHistoryRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIndexRoute: StudentsIndexRoute,
  StudentsStudentIdHistoryRoute: StudentsStudentIdHistoryRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeworkRoute: HomeworkRouteWithChildren,
  InsightsRoute: InsightsRoute,
  StudentsRoute: StudentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
